import React from "react";
import { Platform } from "react-native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createStackNavigator } from "@react-navigation/stack";
import Dashboard from "../ServiceProviderHome/Dashboard";
import Profile from "../ServicePrviderProfile/Profile";
import InboxHome from "../ServiceProviderInbox/InboxHome";
import Inbox from "../ServiceProviderInbox/Inbox";
import Wallet from "../Wallet/Wallet";
import { CustomIcon } from "../../../components/CustomIcon";
import { COLORS } from "../../../utils";
import MyJobScreen from "../ServiceProviderHome/MyJobs/MyJobScreen";
import NewJobScreen from "../ServiceProviderHome/NewJobs/NewJobScreen";
import InProgressScreen from "../ServiceProviderHome/InProgressJobs/InProgressScreen";
import CancelledJobScreen from "../ServiceProviderHome/CancelledJobs/CancelledJobScreen";
import JobDirection from "../ServiceProviderHome/MyJobs/JobDirection";
import EditServiceProviderProfile from "../ServicePrviderProfile/EditServiceProviderProfile";
import ServiceReceipt from "../ServiceProviderHome/InProgressJobs/ServiceReceipt";
import WithdrawFund from "../Wallet/Withdraw/WithdrawFund";
import EditAmount from "../Wallet/Withdraw/EditAmount";
import AddBank from "../Wallet/Withdraw/AddBank";
import AddBankAccount from "../Wallet/Withdraw/AddBankAccount";
import WithdrawSuccess from "../Wallet/Withdraw/WithdrawSuccess";
import ProfileJob from "../ServicePrviderProfile/ProfileJob";
import ProfileManageAvailability from "../ServicePrviderProfile/ProfileManageAvailability";
import ProfileChangePassword from "../ServicePrviderProfile/ProfileChangePassword";
import ProfileHelpCenter from "../ServicePrviderProfile/ProfileHelpCenter";
import ProfileInvoices from "../ServicePrviderProfile/ProfileInvoices";
import ProfileManageRates from "../ServicePrviderProfile/ProfileManageRates";
import ProfileServicesCategories from "../ServicePrviderProfile/ProfileServicesCategories";
import ProfileFaq from "../ServicePrviderProfile/ProfileFaq";
import ProfileShareApp from "../ServicePrviderProfile/ProfileShareApp";
import ProfilePrivacy from "../ServicePrviderProfile/ProfilePrivacy";
import SelectCountry from "../../SharedScreens/Location/SelectCountry";
import SelectState from "../../SharedScreens/Location/SelectState";
import SelectCity from "../../SharedScreens/Location/SelectCity";

